version: '3'

vars:
  CLIENT_SOURCE: "cmd/client.go"
  SERVER_SOURCE: "cmd/main.go"
  CLIENT_BINARY: "client"
  SERVER_BINARY: "server"

tasks:
  client:
    desc: "Compile the client program"
    cmds:
      - go build -o {{.CLIENT_BINARY}} {{.CLIENT_SOURCE}}
    generates:
      - "{{.CLIENT_BINARY}}"

  server:
    desc: "Compile the server program"
    cmds:
      - go build -o {{.SERVER_BINARY}} {{.SERVER_SOURCE}}
    generates:
      - "{{.SERVER_BINARY}}"

  build:
    desc: "Compile both client and server programs"
    cmds:
      - task: client
      - task: server
